// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetConfig():Promise<main.Config>;

export function HideWindow():Promise<void>;

export function IsEnabled():Promise<boolean>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SetEnabled(arg1:boolean):Promise<void>;

export function ShowWindow():Promise<void>;

export function Translate(arg1:string):Promise<string>;
